name: e2e-test-setup

on:
  workflow_dispatch:
  push:
    branches:
      - docker-setup

jobs:
  setup:
    runs-on: ubuntu-24.04
    env:
      DB_DATABASE: aowow
      DB_USER: root
      DB_PASSWORD: root

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Apache
        run: |
          sudo apt-get update
          sudo apt-get install -y apache2
          sudo systemctl enable apache2
          sudo systemctl start apache2
          sudo systemctl status apache2

      - name: Test MySQL connection
        run: sudo mysql -u$DB_USER -p$DB_PASSWORD -e "SHOW DATABASES;"

      - name: Run your tests or scripts
        run: |
          # Run any tests or scripts here
          echo "Test command or script goes here"
