name: generate-aowow-database
on:
  workflow_dispatch:

jobs:
  generate-aowow-db:
    runs-on: ubuntu-24.04
    steps:
      - name: checkout
        uses: actions/checkout@v4
      
      - name: "run acore-docker"
        run: |
          git clone https://github.com/azerothcore/acore-docker
          cd acore-docker
          docker compose up -d

