name: generate-aowow-database
on:
  workflow_dispatch:

jobs:
  generate-aowow-db:
    permissions: write-all
    runs-on: ubuntu-24.04
    steps:
      - name: checkout
        uses: actions/checkout@v4
      
      - name: "run scripts"
        run: |
          git clone https://github.com/azerothcore/acore-docker
          cd acore-docker
          docker compose up -d
          cd ../setup/
          echo "test" >> test.txt
          gh release upload ${{ github.ref_name }} "test.txt"
        # bash generate-db.sh
